print("Hello World!")
print("Hello Again")
print("i like typing this.")
print("This is fun.")
print('Yay! Printing')
print("I'd much rather you 'not'")
print('I "said" do not touch this.')
print("It is used as a comment.")